### ISSUE TITLE
Thoughts on Backform instead of backbone-forms?

### ISSUE THREAD

**Issue by rjsteinert** [enzolutions/generator-marionette-drupal#8]
Hi @enzolutions - Awesome work on this. I'm diving into this generator and thinking about using it for projects. One thing I am wondering, did you have a particular reason to go with Backform as opposed to [backbone-forms](https://github.com/powmedia/backbone-forms)?

\\ RJ

**Comment by enzolutions** [comment]
Hi @rjsteinert I'm glad you consider to use my project.

About your question my decision was related with Backform support to bootstrap and  was easy to implement, easy to extend.

But if you do an implementation with backbore-forms, please do a PR and I will consider the change

**Comment by rjsteinert** [comment]
I will consider doing a pull request, I'm still getting my hands dirty with this generator. It is very ambitious compared to generator-backbone! Yet there are subgenerators like `actions` that I think should be in `generatore-backbone`. This project reminds me of Phreeze, a generator that builds an HTTP Server and a Backbone App (with actions, lists, and forms) from a SQL schema. It might be something to aspire for, or that might be overkill, not sure yet.

http://phreeze.com/cargo/

**Comment by enzolutions** [comment]
Hi @rjsteinert 

Everything is possible, I try to encapsule the concept in the more logical way "my way" that doesn't mean is correct, for that reason I'm totally open to receive contribution.

If you have ideas of better implementation we can discuss
