### ISSUE TITLE
Drupal-side requirements/set up

### ISSUE THREAD

**Issue by stevector** [enzolutions/generator-marionette-drupal#9]
Hello,

I'm trying to test out this generator and I'm getting stuck. I think my problem is on the Drupal side.

Here's what I have so far:
*Drupal 8.0.x*
With the following patches

* Support OPTIONS: https://www.drupal.org/node/2237231#comment-9238891
  * I added this patch while reading https://github.com/enzolutions/backbone.drupal
  * I've also tried the htaccess modifications suggested there
* AuthenticationManager needs interface and ::getProviderKeys https://www.drupal.org/node/2456303
  * I applied that patch because of this issue in the REST UI queue: https://www.drupal.org/node/2456283

Contrib modules:
* REST UI
  * https://www.drupal.org/project/restui
  * Which needed this patch: https://www.drupal.org/node/2456283
* ip_consumer_auth
  * https://github.com/enzolutions/ip_consumer_auth
  * As soon as I enabled this module I got an access denied. As far as I can tell, enabling this module overrides all other authentication plugins thereby logging out the admin user. I was able to hack IPConsumerAuth and at least get to the point where I could sign in. But I couldn't get a positive response in the Marionette App.

![screen shot 2015-04-12 at 2 03 09 pm](https://cloud.githubusercontent.com/assets/211029/7107059/bd3fe8ea-e11c-11e4-82e5-ee02259f8d19.png)

![screen shot 2015-04-12 at 1 58 20 pm](https://cloud.githubusercontent.com/assets/211029/7107066/e0eca63e-e11c-11e4-8846-ce6a986ea416.png)

On the Marionette side I set up a View and an Action to try to load node/1.

During the course of trying to set up the Drupal side I got 401, 403, and 405 responses from the OPTIONS request to node/1. It is not clear to me why an options request is made.

Can you share your Drupal-side environment? Perhaps a dump of your config files and testing DB?

**Comment by enzolutions** [comment]
@stevector what are you trying to do a POST?

**Comment by stevector** [comment]
@enzolutions I don't think I'm trying to use POST specifically. I'm just trying to get any reading of the Drupal site from the Marionette app. So I've made an Action uses a View that should display node 1.

**Comment by stevector** [comment]
I'm just trying to get to a "hello world" level of functionality with a Marionette app reading from a Drupal site.

**Comment by enzolutions** [comment]
can you put you app in a github repo to test in my local?

**Comment by stevector** [comment]
Sure https://github.com/stevector/marionette-generator-test/tree/master

Can you post your Drupal config somewhere?

**Comment by enzolutions** [comment]
Not the generator, I mean the application you have.

Did you apply the changes in .htacess to enable OPTIONS and CORS like I said in https://github.com/enzolutions/backbone.drupal#drupal-8

**Comment by stevector** [comment]
Ok, give me a minute. I'm also on IRC and I could do a Google hangout if it is easier to talk through.

**Comment by enzolutions** [comment]
Try here https://gitter.im/enzolutions/generator-marionette-drupal

**Comment by stevector** [comment]
@enzolutions and I got on a hangout and talk this through. Here are the changes we made.

* On vlad (https://github.com/hashbangcode/vlad) I had to run 
`sudo a2enmod headers` and restart apache with `service apache2 restart` to get cross origin-requests working as described here: https://github.com/enzolutions/backbone.drupal
* ip__consumer_auth does need to be upated to work with D8 HEAD and the most recent beta. https://github.com/enzolutions/ip_consumer_auth/issues/1
* I switched Core to 8.0.0-beta9 instead of HEAD (Although I think that change may have been irrelevant: I still had to apply the patch authenticationmanager-2456303-8.patch to core and and 2456283-3.patch to REST UI.
* I currently do not have the OPTIONS patch from https://www.drupal.org/node/2237231#comment-9238891 applied but I do have in my htaccess:

```
# Intercept OPTIONS calls
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule .* / [R=200,L]
```

@enzolutions I think this issue, or a follow up issue should stay open until this repo has step-by-step instructions for setting up the Drupal side.

**Comment by rjsteinert** [comment]
No luck on my end applying the patch to 8.0.0-beta9
```
 /.../Desktop/drupal-8.0.0-beta9 ♘ wget https://www.drupal.org/files/issues/core-cors-headers-1869548-26.patch
--2015-04-17 15:13:25--  https://www.drupal.org/files/issues/core-cors-headers-1869548-26.patch
Resolving www.drupal.org... 72.21.91.99
Connecting to www.drupal.org|72.21.91.99|:443... connected.
gHTTP request sent, awaiting response... 200 OK
Length: 790 [text/plain]
Saving to: 'core-cors-headers-1869548-26.patch'

core-cors-headers-1869548-26.patch      100%[===============================================================================>]     790  --.-KB/s   in 0.001s

2015-04-17 15:13:26 (796 KB/s) - 'core-cors-headers-1869548-26.patch' saved [790/790]

 /.../Desktop/drupal-8.0.0-beta9 ♘ git apply -v core-cors-headers-1869548-26.patch
Checking patch .htaccess...
Hunk #1 succeeded at 122 (offset 4 lines).
error: while searching for:
    </FilesMatch>
  </IfModule>
</IfModule>

error: patch failed: .htaccess:165
error: .htaccess: patch does not apply
```

If I add the lines manually will this technique still work do you think?

**Comment by enzolutions** [comment]
Hi @rjsteinert 

Sorry for this late response.

The patch for .htaccess doesn't apply anymore due changes in this file. My recommendation is apply the rules manually

1.

After rule  **RewriteRule ^ %1/core/%2 [L,QSA,R=301]**

Add these lines
 ```
# Intercept OPTIONS calls
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule .* / [R=200,L]
```

2. Add end of line include these lines

```
+Header always set Access-Control-Allow-Origin "*"
+Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, PATCH, DELETE"
+Header always set Access-Control-Allow-Headers: Authorization
```

Double check  your apache has header module or run **sudo a2enmod headers**

**Comment by enzolutions** [comment]
I added instructions in this project and Backbone.Drupal to avoid future issues
